### ISSUE TITLE
Comparing version strings issue

### ISSUE THREAD

**Issue by ItsHardToTakeUsername** [Olf0/sfos-upgrade#32] opened 2019-07-20 02:09 UTC
sfos-upgrade fails to work on Inoi R7.

```
[root@Sailfish nemo]#  sfos-upgrade 3.1.0.11
Notice: The installed version 3.0.0.11+omp0.1.3.10 is smaller than the one curr
ently set for SSU (3.1.0.11).
A possible reason for this is, that the \'sailfish-osupdateservice osupdate-che
ck\' invoked by osupdate-check.service (which is regularly triggered by osupdat
e-check.timer) does more than just checking (observed with SailfishOS 3.0.2 and
earlier): E.g., setting ssu to the recent release version or next stop release
.
Never mind, the version for SSU will be set correctly again, later on.

/usr/bin/sfos-upgrade: line 74: [: 11+omp0: integer expression expected
/usr/bin/sfos-upgrade: line 78: [: 11+omp0: integer expression expected
Warning from function compare_versions: Version strings "3.0.0.8" and "3.0.0.11
+omp0.1.3.10" are not comparable!
[root@Sailfish nemo]#
```

**Comment by Olf0** [comment] 2019-07-26 14:56
Oh, `version` outputs an unexpected forrmat of the version string on your Inoi R7: 3.0.0.11+omp0.1.3.10
AFAIK, the version strings of all SailfishOS versions supplied directly by Jolla always were in the format a.b.c.d (e.g. 3.0.0.11), but not a.b.c.d+xyze.f.g.h

As I do not have access to an Inoi R7, I do need more information to understand how to handle this properly.
1. Is this a regular, standard Inoi R7?   I.e., with no special SailfishOS version; just what Inoi distributes to regular (i.e. personal) customers?
2. Have you subscribed to Jolla's "EA (early access) channel?
   I even do not know, if that is possible with a third party SailfishOS device (e.g. by Inoi, Intex, Jala), but obviously so as you tried to install SFOS 3.1 a couple of days ago.
3. Do you know, if Inoi devices always carried such an "+omp<version>" extension of the version string?  ("omp" may mean, "Open Mobile Russia".)
4. Do you know, if it is correct to upgrade at the command line using a regular version string?  Specifically, have you upgraded SailfishOS on your device successfully per `ssu re <a.b.c.d> && version dup` or `sfos-upgrade <a.b.c.d>` in the past?
   I am concerned that their correct usage may be with <a.b.c.d+ompe.f.g.h> on a device as yours.

**Comment by Olf0** [comment] 2019-07-28 12:26
@ItsHardToTakeUsername, ai posted a [RFI at OpenRepos](https://openrepos.net/comment/30164#comment-30164), but nevertheless I still would appreciate feedback from you.

**Comment by Okxa** [comment] 2019-08-12 14:13
I have similiar problems on factory reset Jolla 1. Using `sfos-upgrade-3.1-4.noarch.rpm`

```
[root@Jolla nemo]# sfos-upgrade 3.1.0.11
/usr/bin/sfos-upgrade: line 74: [: : integer expression expected
/usr/bin/sfos-upgrade: line 78: [: : integer expression expected
Warning from function compare_versions: Version strings "(Tahkalampi)" and "1.0.8.19" are not comparable!
```

```
[root@Jolla nemo]# ssu re
Device release is currently: 1.0.8.19
```

```
[root@Jolla nemo]# ssu s
Device registration status: not registered
Device model: Jolla (SbJ / JP-1301)
Device UID: 359745050358065
Release: 1.0.8.19
```

```
[root@Jolla nemo]# version
SailfishOS 1.0.8.19 (Tahkalampi) (armv7hl)
```

**Comment by Olf0** [comment] 2019-08-13 00:18
"Fixed" per commit b8a7645 from PR #33.

Note that, without the above requested information, this is a "shot in the dark": The issue is resolved at the surface, but the consequences are unknown for devices affected by this issue #32!

**Comment by Olf0** [comment] 2019-08-13 21:09
Released as [v3.2-1](https://github.com/Olf0/sfos-upgrade/releases) and uploaded a built [RPM for testing](https://github.com/Olf0/sfos-upgrade/releases/download/3.2-1/sfos-upgrade-3.2-1.noarch.rpm).

**Closed by Olf0** 2019-08-13 21:09 UTC
Labels: enhancement, fixed, need info

**Comment by ItsHardToTakeUsername** [comment] 2019-11-03 13:03
>     1. Is this a regular, standard Inoi R7?   I.e., with no special SailfishOS version; just what Inoi distributes to regular (i.e. personal) customers?
Yes.
>     2. Have you subscribed to Jolla's "EA (early access)" release channel?
No, but I've successfully installed 3.1.0.11 through ssu.
> 
>     3. Do you know, if Inoi devices always carried such an "+omp" extension of the version string?  ("omp" may mean "Open Mobile Russia".)
Yes, it looks like. Now my version is 3.1.0.11+omp0.1.3.13
> 
>     4. a. Do you know, if it is correct to upgrade at the command line using a regular version string on such devices?
Yes, using a regular version string is correct. 
>        b. Specifically, have you upgraded SailfishOS on your device successfully per `ssu re <a.b.c.d> && version dup` or `sfos-upgrade <a.b.c.d>` in the past?
I've upgraded to 3.1.0.11+omp0.1.3.13 through `ssu re 3.1.0.11 && version dup`. But after that I got all sensors broken (light, proximity, accelerometer, compass). All CSD sensors tests are failed. I hope a new update installed through GUI will fix it.
Jolla recommends to use GUI for updating:
> Furthermore, we warmly recommend using the UI for getting updates - the command line way does not have all the necessary checks.
https://together.jolla.com/question/209545/cant-reach-store-repositoryjollacom-and-update-my-sailfishos-cloudflare-issue/?comment=209979#comment-209979

**Comment by Olf0** [comment] 2019-11-03 17:46
Thank you for your reply to [my questions 1 to 4](https://github.com/Olf0/sfos-upgrade/issues/32#issuecomment-515486523) above.  This provides me with a bit more assurance that I did implement this right for Inoi phones.

As nobody has replied to my [RFI at OpenRepos](https://openrepos.net/comment/30164#comment-30164), copying the complete output of `version`, `ssu re` and `ssu s` here would [be still helpful](https://github.com/Olf0/sfos-upgrade/issues/32#issuecomment-515758631) for me (to ensure correctness / double check).

> Jolla recommends to use GUI for updating:

Yes, upgrading at the command line is primarily

* for devices with community builds of SailfishOS, which cannot upgrade at the GUI.
* when upgrading at the GUI fails (on any device).

> Furthermore, we warmly recommend using the UI for getting updates - the command line way does not have all the necessary checks.

Well, upgrading per `ssu re <a.b.c.d> && version dup` provides basically no checks at all, this is exactly why `sfos-upgrade` was created: See [its list of checks in the section **Safety measures**](https://github.com/Olf0/sfos-upgrade#scripts-for-safe-and-automated-upgrading-of-sailfishos-with-logging).

For analysing and resolving your current sensors issue, read [the entry "To ensure that ..." in the section **Notes**](https://github.com/Olf0/sfos-upgrade#scripts-for-safe-and-automated-upgrading-of-sailfishos-with-logging).
If all your SailfishOS upgrades at the command line went flawless, I doubt that upgrading at the GUI would have made a difference.  Still another upgrade may (or may not) resolve this, regardless of the way it is performed.
As the SailfishOS 3.2 GA (general availability) release is near (SFOS 3.2.0.12 was released as EA (early access) last Tuesday), waiting and upgrading at the GUI is a reasonable approach; you can still analyse and try to resolve this at the command line, if the sensors issue persists.
Good luck for your next upgrade and let me know how it went.

**Comment by ItsHardToTakeUsername** [comment] 2019-11-03 20:15
>copying the complete output of `version`, `ssu re` and `ssu s` here would be still helpful
```
[nemo@Sailfish ~]$ version
Sailfish Mobile OS RUS 3.1.0.11+omp0.1.3.13 (Seitseminen)
[nemo@Sailfish ~]$ ssu re
WARNING: ssu.ini does not seem to be writable. Setting values might not work.
Device release is currently: 3.1.0.11
[nemo@Sailfish ~]$ ssu s
WARNING: ssu.ini does not seem to be writable. Setting values might not work.
[D] unknown:0 - "No carrier"
Device registration status: not registered
Device model: INOI R7 (p4903 / P4903)
Device UID: *****
Release: 3.1.0.11
Domain: sales
Brand: Jolla
```
> For analysing and resolving your current sensors issue, read [the entry "To ensure that ..." in the section **Notes**](https://github.com/Olf0/sfos-upgrade#scripts-for-safe-and-automated-upgrading-of-sailfishos-with-logging).
```
[root@Sailfish nemo]# sfos-upgrade "$(version | grep -o '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*')"
Aborting: Inorrect version format "3.1.0.11
0.1.3.13" provided.
```
There are two matches for the regexp :)
Anyway, I can't test sfos-upgrade now because Cloudflare servers that Jolla uses are banned in my mobile network due to weird Russian laws. I'll test it when I reach some Wi-Fi.

**Comment by Olf0** [comment] 2019-11-04 02:04
Thank you for the information (and confirmation, that everything is O.K. for Inoi R7s).

Sorry, I saw this failure coming, but forgot to mention it.  Luckily I already [did this right in sfos-upgrade](https://github.com/Olf0/sfos-upgrade/blob/master/usr/bin/sfos-upgrade#L105).
Using `sfos-upgrade "$(version | grep -o '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*' | sed -n '1p')"` should work, when you have unfiltered WiFi again.

**Comment by Olf0** [comment] 2019-11-04 02:57
Side note & JFYI (because people often wonder that their device is "not registered") the output on an Jolla 1 phone:

    [nemo@lila ~]$ version
    Sailfish OS 2.2.1.18 (Nurmonjoki)
    [nemo@lila ~]$ ssu re
    WARNING: ssu.ini does not seem to be writable. Setting values might not work.
    Device release is currently: 2.2.1.18
    [nemo@lila ~]$ ssu s
    WARNING: ssu.ini does not seem to be writable. Setting values might not work.
    Device registration status: not registered
    Device model: Jolla (SbJ / JP-1301)
    Device UID: *****
    Release: 2.2.1.18
    Domain: sales
    [nemo@lila ~]$

**Comment by ItsHardToTakeUsername** [comment] 2019-11-04 09:58
Also, there is a typo
`Aborting: _Inorrect_ version format`

**Comment by Olf0** [comment] 2019-11-04 13:48
Thank a lot, because it is really hard to see typos in one's one text (I must have read that "inorrect" many ten times, without recognising it is wrong).
Fixed per [commit #ae370fd](https://github.com/Olf0/sfos-upgrade/commit/ae370fdddac2188c49e0e60d05041d9eac1a03df).

**Comment by ItsHardToTakeUsername** [comment] 2019-11-05 22:48
I did `sfos-upgrade 3.1.0.11` and nothing changed. It just says `NO UPDATES FOUND. Try again later.`

<details>
<summary>sfos-upgrade log</summary>

````
[root@Sailfish nemo]# sfos-upgrade 3.1.0.11
Notice: Do you want to ensure this SailfishOS 3.1.0.11 installation to be compl
ete and up to date? (Y/N) y

Notice: For troubleshooting issues with the upgrade proper, please consult http
s://jolla.zendesk.com/hc/en-us/articles/360005795474

- Stopping osupdate-check.timer
- Stopping rpm

- Unapplying all Patchmanager-Patches.

- Setting SSU to SailfishOS release:
Changing release from 3.1.0.11 to 3.1.0.11
Your device is now in release mode!

- Fetching and installing the SailfishOS upgrade from 3.1.0.11 to 3.1.0.11 (thi
s may take a while):
REFRESHING CACHE AND DOWNLOADING PACKAGES
Finished transaction (status=1, runtime=171541ms)
UPGRADING SYSTEM
Finished transaction (status=1, runtime=8704ms)
FINISHING

NO UPDATES FOUND. Try again later.

Notice: After rebooting, do not miss to run post_sfos-upgrade
````
</details>


<details>
<summary>post_sfos-upgrade log</summary>

````
[root@Sailfish nemo]# post_sfos-upgrade
- Cleaning logfiles of duplicate entries.
systemupdate_3.1.0.11-from-3.1.0.11_2019-11-03_23-10-52.log-dupes.txt: O.K.
systemupdate_3.1.0.11-from-3.1.0.11_2019-11-05_15-49-21.log-dupes.txt: O.K.
Summary: Processed 2 untidy log file(s) in /var/log successfully.

- Removing outdated Store version info.

- Refreshing zypper's caches:
Repository 'adaptation0' is up to date.
Repository 'adaptation1' is up to date.
Retrieving repository 'apps' metadata ...................................[done]
Building repository 'apps' cache ........................................[done]
Retrieving repository 'customer-omp-ru' metadata ........................[done]
Building repository 'customer-omp-ru' cache .............................[done]
Retrieving repository 'hotfixes' metadata ...............................[done]
Building repository 'hotfixes' cache ....................................[done]
Retrieving repository 'jolla' metadata ..................................[done]
Building repository 'jolla' cache .......................................[done]
[long list of openrepos repos.......]
Retrieving repository 'sailfish-eas' metadata ...........................[done]
Building repository 'sailfish-eas' cache ................................[done]
Retrieving repository 'store' metadata ..................................[done]
Building repository 'store' cache .......................................[done]
All repositories have been refreshed.

- Refreshing pkcon's caches:
Refreshing cache
Waiting for authentication
Starting
Refreshing software list
Finished
````
</details>

**Comment by Olf0** [comment] 2019-11-06 01:03
Well, this simply means that your installation of SailfishOS 3.1.0.11 is complete and up-to-date, WRT the packages (RPMs) in the enabled repositories.
The repositories list also looks fine to me (see **zypper**'s output of **post_sfos-upgrade**) (while I sure have never seen the *customer-omp-ru* repository before, without an device by Inoi, this is basically configured as I expected).
As you already have **zypper** installed, you may also take look at the output of `zypper verify --dry-run -y`, but I expect it to tell you the same (nothing to do).  If not, refreshing zypper's caches by post_sfos-upgrade made a difference: Rerun sfos-upgrade 3.1.0.11, then.

There also is a [SailfishOS 3.1.0.12 available](https://coderus.openrepos.net/whitesoft/sailversion) with minor changes compared to v3.1.0.11 (which were not well documented; I don't remember if they were related to sensors), but (if) it is not offered at the GUI, Jolla does not suggest it as an upgrade for your device.

I assume you have thoroughly searched [TJC](https://together.jolla.com/questions/), but you may want to search again, taking [Askbot's flaws and workarounds](https://together.jolla.com/question/169977/suggestion-update-the-forum-software-so-it-is-easier-to-findread-relevant-issues/?answer=170000#post-id-170000) into account.
Note that any similar sensors issue for a Jolla C and Intex Aquafish may be relevant for you, as they and the Inoi R7 share the same hardware (except for the cellular modem (firmware)).

BTW, thanks for the log files, it was the first time I had seen the output on a SailfishOS device, which was not configured by me.  Good to know that everything looks as it should.

**Comment by ItsHardToTakeUsername** [comment] 2019-11-06 15:50
>you may also take look at the output of zypper verify --dry-run -y

Hm, there's something interesting
```
Problem: product:# This file is copied as hw-release-0.0.1.21.analogous to os-release is not installable
Solution 1: deinstallation of product:# This file is copied as hw-release-0.0.1.21.analogous to os-release
```
There is a topic on TJC with the same problem and no answers
https://together.jolla.com/question/215758/32012problem-detected-by-zypper-ve-after-upgrade/
Looks like something related to hardware adaptation?..

Also, looks like sfos-upgrade doesn't check `version dup` exit code
```
UPGRADE NOT COMPLETE - Retry 9 of 9
Waiting 30 seconds before retry.
REFRESHING CACHE AND DOWNLOADING PACKAGES
Refreshing: 0%
Error: Timeout exceeded when accessing 'https://store-repository.jolla.com/rele
ases/3.1.0.11/jolla-hw/adaptation-qualcomm-p4903/armv7hl/repodata/repomd.xml?cr
edentials=store'.
Finished transaction (status=2, runtime=62603ms)
FINISHING

The upgrade could NOT be finished. Make sure you have
a working Internet Connection and SSU is propertly set up. In
case the repos are changing rapidly (e.g. during development),
just restarting the upgrade might fix the issue.

REBOOT AT YOUR OWN RISK.

Notice: After rebooting, do not miss to run post_sfos-upgrade
```

**Comment by Olf0** [comment] 2019-11-06 22:08
> Hm, there's something interesting

ACK.

> Looks like something related to hardware adaptation?

Yes, although IMO likely not directly, but that may cause the real Hardware Adaptation to be misconfigured.

> There is a topic on TJC with the same problem and no answers

Well, you may "answer" this question, stating that you also see this on your Inoi R7 with SailfishOS 3.1.0.11 and ask the OP ("original post(er)"), if he observes the same effects (<description of your sensors issues>).
The first part might be relevant for Jolla, the second may provide you with a reply confirming (or not) that zypper's complaint and the sensors issues are related.

**Comment by Olf0** [comment] 2019-11-06 22:20
> Also, looks like sfos-upgrade doesn't check `version dup` exit code

[It does](https://github.com/Olf0/sfos-upgrade/blob/master/usr/bin/sfos-upgrade#L732), but `version` does not pass the return code from `/usr/bin/rnd-dist-upgrade` / `pkcon`: see `cat /usr/bin/version`

**Comment by Olf0** [comment] 2020-01-16 21:29
Original [Intex Aqua Fish (l500d)](https://openrepos.net/comment/32258#comment-32258) by scanner@openrepos.net:
```
version
SailfishOS 2.1.4.14 (Lapuanjoki)

ssu re
WARNING: ssu.ini does not seem to be writable. Setting values might not work.
Device release is currently: 2.1.4.14

ssu s
WARNING: ssu.ini does not seem to be writable. Setting values might not work.
Device registration status: not registered
Device model: Intex Aqua Fish (l500d / Aqua Fish)
Device UID: ***
Release: 2.1.4.14
Domain: sales
```

**Comment by hooddy** [comment] 2023-08-09 09:05
Guys... I have INOI R7 and can't update it even to 3.1.0.11 from 3.0.0.11. OTA always say it's up to date.
