### ISSUE TITLE
[Bug] script exits silently when current release isn't detected.

### ISSUE THREAD

**Issue by nephros** [Olf0/sfos-upgrade#71] opened 2022-09-30 15:59 UTC
**SailfishOS VERSION** (Settings → About product → Build): 4.4.0.64
<br />**HARDWARE** (Settings → About product → Manufacturer & Product name): Xperia 10iii
<br />**sfos-upgrade VERSION** ( `rpm -qi sfos-upgrade` ): 3.9.9-release3
<br />

#### BUG DESCRIPTION
Update to 4.4.0.72 not detected

#### STEPS TO REPRODUCE
run

      sfos-upgrade 4.4.0.72

observe that nothing happens at all. No error msg, no updating, just nothing.

#### ADDITIONAL INFORMATION

From doing things like `sh -x` it tuens out the release is not yet listed in the docs.s.o wiki/site. So the parsing done by the script fails.

Snippet if the last few lines of `sh -x sfos-update 4.4.0.72`:

```
1.0.0.3
1.0.0.1
0.99.6.8
0.99.6.3
0.99.5.11
0.99.5.8
0.99.5.6'
++ curl -sSkL https://github.com/sailfishos/docs.sailfishos.org/raw/master/Releases/README.md
++ cut -s -d '|' -f 2,5
++ tr -d ' '
+ sailfishdocs_sfos_list=
++ echo ''
++ cut -s -d '|' -f 1
++ grep '^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$'
+ sailfishdocs_sfos_releases=
```

I realize that is not the fault of the script.

But it should output *something* in this case, not silently exit.

<Please consider which other pieces of information may be relevant: Denote if this is not always reproducible, if this is a regression (then name to which older version), attach relevant data such as log files or the systemd journal, provide text output via copy & paste or output-redirecton (no screenshots, please!) etc.>

**Comment by nephros** [comment] 2022-09-30 16:05
And it turns out `https://github.com/sailfishos/docs.sailfishos.org/raw/master/Releases/README.md` does not actually exist any more, so that is the root cause.

**Comment by Olf0** [comment] 2022-09-30 19:21
> https://github.com/sailfishos/docs.sailfishos.org/raw/master/Releases/README.md

Thanks.  Still I always prefer the shorter version (here: https://github.com/sailfishos/docs.sailfishos.org/raw/master/Support/Releases/README.md ) which redirects to the location at https://raw.githubusercontent.com/sailfishos/docs.sailfishos.org/master/Support/Releases/README.md

Applied per [commit c86f061](https://github.com/Olf0/sfos-upgrade/commit/c86f061dbed124204b75317e078277c57ce8460b).

**Comment by Olf0** [comment] 2022-09-30 20:07
> From doing things like `sh -x` it tuens out the release is not yet listed in the docs.s.o wiki/site. So the parsing done by the script fails.
> 
> Snippet if the last few lines of `sh -x sfos-update 4.4.0.72`:
> 
> ```
> 1.0.0.3
> 1.0.0.1
> 0.99.6.8
> 0.99.6.3
> 0.99.5.11
> 0.99.5.8
> 0.99.5.6'
> ++ curl -sSkL https://github.com/sailfishos/docs.sailfishos.org/raw/master/Releases/README.md
> ++ cut -s -d '|' -f 2,5
> ++ tr -d ' '
> + sailfishdocs_sfos_list=
> ++ echo ''
> ++ cut -s -d '|' -f 1
> ++ grep '^[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*$'
> + sailfishdocs_sfos_releases=
> ```
> 
> I realize that is not the fault of the script.
> 
> But it should output _something_ in this case, not silently exit.

<br />
That *is* this script's fault!

I think it is caused by `set -e` and the `grep` returning an exit code not equal to `0`, because it fails to grep anything (from an empty string).

[Commit 59c0d96](https://github.com/Olf0/sfos-upgrade/commit/59c0d96f8b6148252f5461814aedbe090c67a1f0) should fix this.
<sub>Please review, if you have time for that, as I am currently dumbed by pain and painkillers.</sub>

**Comment by nephros** [comment] 2022-09-30 22:09
> 
> [Commit 59c0d96](https://github.com/Olf0/sfos-upgrade/commit/59c0d96f8b6148252f5461814aedbe090c67a1f0) should fix this. Please review, if you have time for that, as I am currently dumbed by pain and painkillers.

uhm that doesn't look right to me.

You're doing a

    if foo=bar

without brackets, that's always going to be true isn't it. Shouldn't it be

    if [ $foo = $bar ]

or something similar?

**Comment by Olf0** [comment] 2022-10-02 10:49
Oh, it's Shell code:
- An `if` statement simply evaluates the return code of the command, which is provided as parameter.
- A `0` is interpreted as "true", any other return code as "false".<br /><sub>BTW, `true`is simply a command always returning  `0`.</sub>
- `[` is just an alias for the `test` command, the closing bracket (`]`) is optional.
- If the command is an compound command, the final return code is evaluated; this is why the shell option `-o pipefail` makes the difference between evaluating the return code of the last command of a pipe (`|`) or of the last failing command in a pipe (if any fails).<br /><sub>Side note: For commands compounded by `&&` and / or `||` the behaviour is implicit.</sub>
- Variable assignments (`=`), variable substitutions (`$()` / `\`\``), flow control (`if`, `then`, `else`, `elif`, `for`, `while`, `do` etc.) etc. are not "commands".
- Because `-o pipefail` is not set yet (the default), here the return code of a `grep` is evaluated.

**Comment by Olf0** [comment] 2022-10-02 13:04
[v3.9.11](https://github.com/Olf0/sfos-upgrade/releases/tag/3.9.11) should fix this.

**Closed by Olf0** 2022-10-02 13:04 UTC
Labels: bug
